src/DEE/FtpBundle/Entity/FtpFileCategory.php
<?php

namespace DEE\FtpBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * FtpFileCategory
 *
 * @ORM\Table(name="ftp_file_category")
 * @ORM\Entity(repositoryClass="DEE\FtpBundle\Repository\FtpFileCategoryRepository")
 */
class FtpFileCategory
{ 
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="label", type="string", length=100, unique=true)
     * 
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     * @Assert\Length(max=100)
     */
    private $label;
    
    /**
     * @var int : number of copies needed to register student to the exams
     *
     * @ORM\Column(name="nb_of_copies", type="integer", nullable=true)
     * 
     * @Assert\Regex(pattern="/^\d*$/", message="Vous devez entrer un nombre")
     */
    private $nbOfCopies;

    /**
     * @var int
     *
     * @ORM\Column(name="validityPeriod", type="integer", nullable=true)
     * 
     * @Assert\Regex(pattern="/^\d*$/", message="Vous devez entrer un nombre")
     */
    private $validityPeriod;

    /**
     * @var string
     *
     * @ORM\Column(name="ftpDirectory", type="string", length=255, nullable=false)
     * 
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     * @Assert\Regex(pattern="/^docs\/[a-z]+\/$/")
     */
    private $ftpDirectory;
    
    /**
     * @var string array
     * 
     * @ORM\Column(name="authorized_extensions", type="array", nullable=false)
     * 
     * @Assert\NotBlank()
     */
    private $authorizedExtensions;
    
    public function __construct() {
        $this->authorizedExtensions = array();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set label
     *
     * @param string $label
     *
     * @return FtpFileCategory
     */
    public function setLabel($label)
    {
        $this->label = $label;

        return $this;
    }

    /**
     * Get label
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Set validityPeriod
     *
     * @param integer $validityPeriod
     *
     * @return FtpFileCategory
     */
    public function setValidityPeriod($validityPeriod)
    {
        $this->validityPeriod = $validityPeriod;

        return $this;
    }

    /**
     * Get validityPeriod
     *
     * @return int
     */
    public function getValidityPeriod()
    {
        return $this->validityPeriod;
    }

    /**
     * Set ftpDirectory
     *
     * @param string $ftpDirectory
     *
     * @return FtpileCategory
     */
    public function setFtpDirectory($ftpDirectory)
    {
        $this->ftpDirectory = $ftpDirectory;

        return $this;
    }

    /**
     * Get ftpDirectory
     *
     * @return string
     */
    public function getFtpDirectory()
    {
        return $this->ftpDirectory;
    }
    
    /**
     * Get number of copies needed
     * 
     * @return int
     */
    function getNbOfCopies() {
        return $this->nbOfCopies;
    }

    /**
     * Set number of copies needed
     * 
     * @param type $nbOfCopies
     */
    function setNbOfCopies($nbOfCopies) {
        $this->nbOfCopies = $nbOfCopies;
    }
    
    /**
     * Get authorized extensions
     * 
     * @return string array
     */
    function getAuthorizedExtensions() {
        return $this->authorizedExtensions;
    }
    
    /**
     * Get authorized extensions in a string
     * If extension has been inserted into db with fixtures : it's a simple array
     * If it has been inserted with doctrine orm : it's an array containing the extensions array
     * 
     * @return string 
     */
    function getAuthorizedExtensionsToString() {
        
        if (is_string($this->authorizedExtensions[0])) {
            return (string) implode(', ',$this->authorizedExtensions);
        } else if (is_array($this->authorizedExtensions[0])) {
            return (string) implode(', ',$this->authorizedExtensions[0]);
        }
    }

    /**
     * Set authorized extensions
     * 
     * @param type $authorizedExtensions
     */
    function setAuthorizedExtensions($authorizedExtensions) {
        if (!in_array($authorizedExtensions, $this->authorizedExtensions, true)) {
            $this->authorizedExtensions[] = $authorizedExtensions;
        }

        return $this;
    }
    
    /**
     * Check if the extension is in authorized extensions array
     * @param string $extension
     * @return bool true if it's in array, or false if it's not
     */
    function isExtensionValid($extension) {
        $inArray = false;
        foreach($this->getAuthorizedExtensions() as $authorizedExtensionArray) {
            if (in_array(strtolower($extension), $authorizedExtensionArray)) { $inArray = true; }
        }
        return $inArray;
    }
}

src/DEE/FtpBundle/Controller/CategoryController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace DEE\FtpBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;

use DEE\FtpBundle\Entity\FtpFileCategory;
use DEE\FtpBundle\Form\FtpFileCategoryType;


/**
 * Controller regarding all ExamCategory actions available
 *
 * @author Delphine Gauthier [at]DEE
 */
class CategoryController extends Controller {
    
    /**
     * Send all ExamCategorys and add form to view
     * Persists new ExamCategory 
     * 
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function indexAction(Request $request) {
        $validForm = true;
        
        // Create student form
        $FileCategory = new FtpFileCategory();
        $form = $this->createForm(FtpFileCategoryType::class, $FileCategory);
        
        // Manage form if it has been filled and return ajax response
        if ($request->isMethod('POST')) {
            if($form->handleRequest($request)->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($FileCategory);
                $entityManager->flush();
            } else {
                $validForm = false;
            }
        }
        
        // Get all exam types
        $categoryRepository = $this->getDoctrine()->getManager()->getRepository('DEEFtpBundle:FtpFileCategory');
        $FileCategories = $categoryRepository->findAll();
        
        return $this->render('DEEFtpBundle:Category:index.html.twig'
                            , array('FileCategories' => $FileCategories, 'form' =>$form->createView(), 'validForm' => $validForm));
    }
    
    /**
     * Delete an ExamCategory in database
     * @return JSONResponse success tag
     * 
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteAction($id) {

        // Get ExamCategory
        $entityManager = $this->getDoctrine()->getManager();
        $CategoryRepository = $entityManager->getRepository('DEEFtpBundle:FtpFile');
        $FileCategory = $entityManager->find(FtpFileCategory::class, $id);
        
        $files  = $CategoryRepository->findBy(array('category' => $FileCategory));
        
        if (count($files) > 0) {
            return new JsonResponse(array('success' => false));
        } else {
            // Deactivate user
            $entityManager->remove($FileCategory);
            $entityManager->flush();

            return new JsonResponse(array('success' => true));
        }
    }
}

src/DEE/FtpBundle/Resources/views/Category/index.html.twig
{# DEE/FtpBundle/Resources/views/Category/index.html.twig #}

{% extends ":backend:layout.backend.html.twig" %}

{% block body %}
   <div class="row margin-top-sm">
        <h1 class="col-xs-12 center-text pointer" id="toggle-FileCategory-form"><span class="fa fa-plus-circle green-text"></span>    Ajouter un type de fichier</h1>
    </div>
    <div class="row margin-top-sm {% if validForm %} {{ "valid-form" }} {% endif %}" id="hidden-FileCategory-form" data-url="{{ path('dee_filecategory_index') }}">
        {{ form(form) }}
    </div>
    <div class="row margin-top-sm">
        <h1 class="col-xs-12 center-text">Liste des types de fichiers</h1>
    </div>
    <div class="row margin-top-sm">
        <table class="table" data-url="{{ path('dee_filecategory_delete',{'id': 0}) }}">
            <tr>
                <th>#</th>
                <th>Label</th>
                <th>Nombre de copies requises</th>
                <th>Période de validité</th>
                <th>Répertoire FTP</th>
                <th>Extensions autorisées</th>
                <th>&nbsp;</th>
            {% for FileCategory in FileCategories %}
                <tr id="{{ FileCategory.id }}">
                    <td>{{ FileCategory.id }}</td>
                    <td>{{ FileCategory.label }}</td>
                    <td>{{ FileCategory.nbOfCopies == null ? "Aucune" : FileCategory.nbOfCopies }}</td>
                    <td>{{ FileCategory.validityPeriod == null ? "Aucune" : FileCategory.validityPeriod~" ans" }}</td>
                    <td>{{ FileCategory.ftpDirectory }}</td>
                    <td>{{ FileCategory.authorizedExtensionsToString }}</td>
                    <td class="fa fa-1-5x pointer fa-times-circle delete-link" data-url="{{ path('dee_filecategory_delete',{'id': FileCategory.id}) }}"  title="Supprimer le type de fichiers">&nbsp;</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}   

{% block requirejs %} 
    {{ include('DEEFtpBundle::_requirejs.html.twig', {
            module: 'app/showFileCategories'
        }) }}
{%endblock%}